# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
import numpy as np
# Age = 23
np.random.randint(10,24,23)


array([13, 17, 13, 13, 17, 18, 18, 22, 18, 12, 15, 21, 12, 11, 23, 23, 19,
       18, 19, 15, 16, 12, 10])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
a = np.arange(1,50,2)
print("Array :",a)

#print("Array Size : ",a.size)
print("Array Size : ",len(a))

Array : [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Array Size :  25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
np.linspace(4,7,27)


array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:
rand_array = np.random.rand(5,4)
np.round(rand_array,2)

array([[0.83, 0.2 , 0.24, 0.83],
       [0.38, 0.74, 0.51, 0.31],
       [0.4 , 0.25, 0.39, 0.94],
       [0.42, 0.05, 0.81, 0.95],
       [0.88, 0.48, 0.25, 0.79]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [5]:
np.random.randint(5,16,(5,5))


array([[15, 13, 13, 15,  7],
       [10, 12, 14, 13,  5],
       [13,  8, 12, 14, 11],
       [ 7,  9,  9, 12, 10],
       [12, 13,  8, 14,  9]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [6]:
np.zeros(np.random.randint(20),dtype='int32')

array([0])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [7]:
r = np.random.randint(1,20)
c = np.random.randint(1,20)
print(r,c)
np.ones((r,c), dtype = 'float32')


16 11


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [8]:
ar = np.array([[9,25,50,34,45],
          [3,34,34,65,2],
          [5,7,3,76,3],
          [7,8,6,54,6],
          [23,12,8,5,8]])
print("shape :",ar.shape)
print("type  :",type(ar))
print("dtype :",ar.dtype)

shape : (5, 5)
type  : <class 'numpy.ndarray'>
dtype : int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [9]:

r = int(len(ar)/2)     #center row
c = int(len(ar.T)/2)   #center column
print("center pixel of the matrix: ",ar[r,c])

center pixel of the matrix:  3


#### 10. Print the all the elements of 3rd row of the matrix

In [10]:
print("3rd row of the matrix : ")
print(ar[2,:])

3rd row of the matrix : 
[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [11]:
print("4th column of the matrix : ")
print(ar[:,3])


4th column of the matrix : 
[34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [12]:
print("Corner pixels of the matrix are : ")
print(ar[0,0],ar[0,-1],ar[-1,0],ar[-1,-1])

Corner pixels of the matrix are : 
9 45 23 8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [13]:
m1 = ar[:2,2:4]
print("m1=",m1)

m2 = ar[3:,:2]
print("\nm2=",m2)

m3 = ar[2:,2:]
print("\nm3=",m3)

m1= [[50 34]
 [34 65]]

m2= [[ 7  8]
 [23 12]]

m3= [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [14]:
# Can be done using ravel or flatten. 
#Ravel -->  Creates a view of the original array
#flatten --> Creates a copy of the array

print("m1 :",np.ravel(m1))
print("m2 :",np.ravel(m2))
print("m3 :",np.ravel(m3))

m1 : [50 34 34 65]
m2 : [ 7  8 23 12]
m3 : [ 3 76  3  6 54  6  8  5  8]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [15]:
print("---Vertical---")
print(np.concatenate((m1,m2),axis=0))
print("---Horizontal---")
print(np.concatenate((m1,m2),axis=1))

---Vertical---
[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
---Horizontal---
[[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [16]:
print("Add :\n",m1+m2)
print("Subtract :\n",m1-m2)
print("Multiply :\n",m1*m2)
print("Divide :\n",m1/m2)

Add :
 [[57 42]
 [57 77]]
Subtract :
 [[43 26]
 [11 53]]
Multiply :
 [[350 272]
 [782 780]]
Divide :
 [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [17]:
new_m3 = np.delete(m3,0,0)
new_m3 = np.delete(new_m3,-1,1)
print("m1: \n",m1)
print("m3: \n",m3)
print("new m3:\n ",new_m3)
print("Addition result : ")
print(m1+new_m3)

m1: 
 [[50 34]
 [34 65]]
m3: 
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]
new m3:
  [[ 6 54]
 [ 8  5]]
Addition result : 
[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [18]:
m1_mean = m1.mean(axis=0)
m1_mean = m1_mean.reshape(1,2)
m4=np.concatenate((m1,m1_mean),axis=0)
m4

array([[50. , 34. ],
       [34. , 65. ],
       [42. , 49.5]])

#### 19. Perform the matrix multiplication between m3 and m4

In [19]:
#print(np.dot(m3,m4))
print(np.matmul(m3,m4))

[[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [20]:
mean_ar = ar.mean(axis=1)
var_ar = ar.var(axis=1)
sd_ar = ar.std(axis=1)

print("------Mean------")
print(mean_ar,"\n")
print("Max:",mean_ar.max(),"\nMin:",mean_ar.min(),"\n")
print("----Variance----")
print(var_ar,"\n")
print("Max:",var_ar.max(),"\nMin:",var_ar.min(),"\n")
print("----Standard Deviation----")
print(sd_ar,"\n")
print("Max:",sd_ar.max(),"\nMin:",sd_ar.min())

------Mean------
[32.6 27.6 18.8 16.2 11.2] 

Max: 32.6 
Min: 11.2 

----Variance----
[214.64 548.24 820.16 357.76  39.76] 

Max: 820.1600000000001 
Min: 39.760000000000005 

----Standard Deviation----
[14.65059726 23.41452541 28.63843571 18.91454467  6.30555311] 

Max: 28.63843571147 
Min: 6.305553108173779


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [21]:
runs = np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
balls = np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])

strike_rate = (runs/balls)*100

print("Average of each player in descending order :")
print(np.sort(runs.mean(axis=1))[::-1],"\n")
print("Average Strike rate of each player in descending order : ")
print(np.sort(strike_rate.mean(axis=1))[::-1])


Average of each player in descending order :
[53.5  51.5  47.25 29.   13.25] 

Average Strike rate of each player in descending order : 
[162.99554687  94.91125541  81.69675643  62.17703913  47.96296296]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [22]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
passed=(marks>=50).sum()
failed = len(marks)-passed
print("Number of students passed :",passed)
print("Number of students failed :",failed)

Number of students passed : 7
Number of students failed : 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [23]:
#Grace marks
ind = np.where((marks<50)&(marks>=45))
marks[ind] = marks[ind] + 5

#Bonus marks
ind1 = np.where(marks>80)
marks[ind1] = marks[ind1] + 5

#Marks > 100
ind2 = np.where(marks>100)
marks[ind2]=100
print("New Marks:",marks)

#pass percentage increase
new_passed = (marks>=50).sum()
increase = ((new_passed-passed)/passed)*100
print("Percentage Increase:",increase,"%")

New Marks: [ 65  89  52  56  94 100  53  77  80  39]
Percentage Increase: 28.57142857142857 %


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [24]:
import time

# Executing expression using list
start_time = time.time()
x = list(range(1,60000))
y = list(range(1,60000))
output = []
for i in range(len(x)):
    output.append(((x[i]**2)+8)/y[i])
end_time = time.time()
print("Time taken for list to execute : ",end_time-start_time)


# Executing expression using array
start_time = time.time()
x = np.arange(1,60000)
y = np.arange(1,60000)
output = ((x**2)+8)/y
end_time = time.time()
print("Time taken for array to execute : ",end_time-start_time)


Time taken for list to execute :  0.08900618553161621
Time taken for array to execute :  0.006000995635986328


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [25]:
#Git Hub account created and file has been uploaded

#https://github.com/lavanya-u/MTech-Python.git